### ISSUE TITLE
Build Failed. when constructor has non column property at Kotlin.

### ISSUE THREAD

**Issue by kenz** [maskarade/Android-Orma#438]
Build the below code, the result is fail.
``` kotlin
@Table
class OrmaTodo(
        @Setter("id") @PrimaryKey var id: Long,
        @Setter("foo") @Column var foo: String,
        var bar:Int? = null
)
```

Error message is not accurate why bar field was not @Setter constructor parameter.
> Error:(51, 2) error: [OrmaProcessor] The @Setter constructor parameters must satisfy all the @Column fields

**Comment by k-kagurazaka** [comment]
Orma requires one of the following to construct a model instance.

1. no-arg constructor and `@Setter` annotated setter methods for all column fields in Java code
2. `@Setter` annotated constructor with all column parameters in Java code

The code based on 1. is following:

```kotlin
@Table
class OrmaTodo(
        @set:Setter("id") @PrimaryKey var id: Long = -1,
        @set:Setter("foo") @Column var foo: String = "",
        var bar: Int? = null
)
```

If you don't like to specify the default value to all column fields, you create a `@Setter` annotated constructor that takes only column parameters since Java doesn't have the default argument feature.

```kotlin
@Table
class OrmaTodo(
        @PrimaryKey var id: Long,
        @Column var foo: String,
        var bar: Int?
) {
    @Setter constructor(id: Long, foo: String) : this(id, foo, null)
}
```

**Comment by k-kagurazaka** [comment]
Hi @kenz .
We have improved to support Kotlin model class with default parameters by #439 .
From the next version, we can declare more concise models as following:

```kotlin
@Table
class OrmaTodo @JvmOverloads @Setter constructor(
        @PrimaryKey var id: Long,
        @Column var foo: String,
        var bar: Int? = null
)
```

We'll close this issue after the next version is published.
Thanks for your feedback!
